# Numpy

**Relembrando**  
  
A biblioteca **NumPy** _(Numerical Python)_ proporciona uma forma eficiente de armazenagem e processamento de conjuntos de dados, e é utilizada como base para a construção da biblioteca Pandas, que estudaremos a seguir.

O diferencial do Numpy é sua velocidade e eficiência, o que faz com que ela seja amplamente utilizada para computação científica e analise de dados. 

A velocidade e eficiência é possível graças à estrutura chamada **numpy array**, que é um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

In [1]:
# A gente importa o numpy sempre chamando ele de "np"
import numpy as np

In [2]:
py_array = [1,  2,  3]

np_array = np.array(py_array)

print(np_array)
print(type(np_array))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
print(type(np_array[0]))

<class 'numpy.int32'>


In [4]:
# Vamos fazer uma comparação com um vetor do numpy
py_matriz = [[1,   2,  3],
            [4,   5,  6],
            [7,   8,  9],
            [10, 11, 12]]

np_matriz = np.array(py_matriz)

print(np_matriz)
print(type(np_matriz))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


In [5]:
np_matriz[0]

array([1, 2, 3])

In [6]:
print(type(np_matriz[0]))

<class 'numpy.ndarray'>


In [7]:
print(type(np_matriz[0][0]))

<class 'numpy.int32'>


In [8]:
# 3 atributos básicos pra um ndarray
print(np_matriz.shape)   # O formato dele
print(np_matriz.ndim)    # Quantas dimensões ele tem
print(np_matriz.dtype)   # O "dtype", que é o tipo dos elementos (número, letra, ...) dele

(4, 3)
2
int32


In [9]:
x = np.array([1, 2, 3]) # Um vetor também é um ndarray
print(type(x))
print(x.dtype)

<class 'numpy.ndarray'>
int32


In [10]:
# O dtype de um array do numpy pode ser controlado na hora que a gente cria.
py_matriz = [[1,   2,  3],
            [4,   5,  6],
            [7,   8,  9],
            [10, 11, 12]]

matriz = np.array(py_matriz, dtype=np.float64)

In [11]:
print(matriz)
print(matriz.dtype)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
float64


In [12]:
# Para selecionar um elemento de uma tabela no Python e no Numpy, tem uma ligeira diferença.
print((matriz[0][0])) # Python: Pega a primeira linha. Dela, pega o primeiro elemento.
print((matriz[0, 0]))  # Numpy: Pega o elemento da linha 0, coluna 0.

1.0
1.0


Slicing com matriz

In [21]:
x = [1, 2, 3, 4, 5, 6, 7, 8] # Um vetor também é um ndarray
x

[1, 2, 3, 4, 5, 6, 7, 8]

In [23]:
x[0:9:2]

[1, 3, 5, 7]

In [13]:
# Slicing funciona no numpy!
print(matriz)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [25]:
print(matriz[:,1:]) 
print('------')
print(matriz[1,:]) 
print('------')
print(matriz[1,::-1]) 

[[ 2.  3.]
 [ 5.  6.]
 [ 8.  9.]
 [11. 12.]]
------
[4. 5. 6.]
------
[6. 5. 4.]


**Funções numpy**  
O numpy também tem diversas funções para facilitar criação de matrizes.

In [26]:
print(np.zeros((10, 3)), end='\n\n') # O "end" muda o que o Python encaixa no fim do que ele mostra pra gente.
print(np.ones((5,2)), end='\n\n') # \n é pular linha, e é o default. \n\n pula 2 linhas.
print(np.identity(4), end='\n\n')
print(np.eye(4, 3), end='\n\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]



# Manipulações de matrizes

In [27]:
matriz

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [28]:
# Transposição de matrizes
matriz.T

array([[ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  6.,  9., 12.]])

In [29]:
array_transposto = np.transpose(matriz)
array_transposto

array([[ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  6.,  9., 12.]])

In [30]:
matriz.transpose()

array([[ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  6.,  9., 12.]])

In [31]:
x = np.array([0.1, 0.4, 1.0, 0.2, 0.7, 1.2, 1.1, 1.0, 0.9])
x.shape

(9,)

In [32]:
# Redimensionamento
x.reshape(3, 3)

array([[0.1, 0.4, 1. ],
       [0.2, 0.7, 1.2],
       [1.1, 1. , 0.9]])

In [33]:
y = np.array([0.1, 0.4, 1.0, 0.2, 0.7, 1.2, 1.1, 1.0, 0.9, 2.0, 1.5, 1.6])
y.shape

(12,)

In [34]:
# Vejam o que acontece se as dimensões não são condizentes
y.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [41]:
# E se eu quiser retornar para um vetor
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

x.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
# Também é possível utilizar o flatten
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# Também podemos combinar arrays diferentes.
# Imagina que temos duas features, altura e peso de pessoas físicas.
x1 = np.array([[1.67, 89.],
               [1.79, 85.],
               [1.69, 65.],
               [1.54, 57.],
               [1.50, 45.]])

# Porém, nós queremos testar agora adicionar uma terceira feature, se a pessoa é homem ou mulher.
# 1 é mulher, 0 é homem
x2 = np.array([1, 0, 1, 0, 1])

# Como podemos fazer?

In [47]:
x2

array([1, 0, 1, 0, 1])

In [46]:
x2.reshape(-1, 1)

array([[1],
       [0],
       [1],
       [0],
       [1]])

In [50]:
#Podemos utilizar o concatenate
np.concatenate((x1, x2.reshape(-1, 1)), axis=1) # O valor -1 no reshape significa que não sabemos quantas linhas teremos, o próprio numpy irá definir

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [56]:
np.append(x1, x2.reshape(-1, 1), axis=1) 

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [57]:
np.insert(x1, 1, x2, axis=1)

array([[ 1.67,  1.  , 89.  ],
       [ 1.79,  0.  , 85.  ],
       [ 1.69,  1.  , 65.  ],
       [ 1.54,  0.  , 57.  ],
       [ 1.5 ,  1.  , 45.  ]])

In [58]:
np.vstack([x1.T, x2])

array([[ 1.67,  1.79,  1.69,  1.54,  1.5 ],
       [89.  , 85.  , 65.  , 57.  , 45.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  1.  ]])

In [59]:
np.vstack([x1.T, x2]).T

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [60]:
np.hstack([x1, x2.reshape(-1, 1)])

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [61]:
np.column_stack([x1, x2])

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [62]:
# Agora temos a tabela de dados abaixo.
table = np.array([[1.67, 89., 1],
                  [1.79, 85., 0],
                  [1.69, 65., 1],
                  [1.54, 57., 0],
                  [1.50, 45., 1]])

# Mas tinhamos esquecido de outras 3 pessoas!
new_table = np.array([[1.78, 91, 0],
                      [1.72, 67, 1],
                      [1.77, 76, 1]])

In [63]:
# Como podemos juntar as tabelas?
np.vstack([table, new_table])

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ],
       [ 1.78, 91.  ,  0.  ],
       [ 1.72, 67.  ,  1.  ],
       [ 1.77, 76.  ,  1.  ]])

In [64]:
np.append(table, new_table, axis=0)

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ],
       [ 1.78, 91.  ,  0.  ],
       [ 1.72, 67.  ,  1.  ],
       [ 1.77, 76.  ,  1.  ]])

In [67]:
np.append(table, new_table)

array([ 1.67, 89.  ,  1.  ,  1.79, 85.  ,  0.  ,  1.69, 65.  ,  1.  ,
        1.54, 57.  ,  0.  ,  1.5 , 45.  ,  1.  ,  1.78, 91.  ,  0.  ,
        1.72, 67.  ,  1.  ,  1.77, 76.  ,  1.  ])

In [68]:
np.append(table, new_table).reshape(-1, 3)

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ],
       [ 1.78, 91.  ,  0.  ],
       [ 1.72, 67.  ,  1.  ],
       [ 1.77, 76.  ,  1.  ]])

# Operações Básicas

In [69]:
vec1 = np.arange(0, 10, 1)
print(vec1)
print(vec1 * 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [70]:
matriz

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [71]:
#Podemos multiplicar por um escalar
matriz_dobro = 2 * matriz
matriz_dobro

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.],
       [20., 22., 24.]])

In [72]:
# Podemos somar duas matrizes
print(matriz + matriz_dobro)

[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]


In [73]:
# Multiplicação elemento por elemento
print(matriz * matriz_dobro)

[[  2.   8.  18.]
 [ 32.  50.  72.]
 [ 98. 128. 162.]
 [200. 242. 288.]]


![](./images/mult_matriz.jpeg)

In [74]:
print(matriz.shape)
print(matriz_dobro.shape)

(4, 3)
(4, 3)


In [75]:
# Produto matricial
print(matriz @ matriz_dobro.T)

print('----------------------------')
# Outra forma de escrever a mesma coisa
print(matriz.dot(matriz_dobro.T))

[[ 28.  64. 100. 136.]
 [ 64. 154. 244. 334.]
 [100. 244. 388. 532.]
 [136. 334. 532. 730.]]
----------------------------
[[ 28.  64. 100. 136.]
 [ 64. 154. 244. 334.]
 [100. 244. 388. 532.]
 [136. 334. 532. 730.]]


**Bora praticar!**  
  
Transforme o csv **dados_artificiais**, que está na pasta **dados**, para um numpy array (matriz)

In [77]:
lista_artificial = 
[[1.788810693, 65.64810194, 0],
[1.566784434, 76.64276798, 0],
[2.092193055, 55.46818533, 1],
[1.782470917, 67.28199736, 1],
[1.735766977, 69.28900763, 0],
[1.686974648, 56.84005114, 0],
[1.797104633, 65.20897328, 1],
[1.187349055, 48.16476395, 0],
[1.595891436, 45.41064814, 1],
[1.396281776, 67.93011334, 0],
[1.606148165, 67.71960410, 0],
[1.707589967, 45.60933262, 0],
[1.735513116, 64.84545151, 0],
[1.672055182, 39.70595150, 1],
[1.723377069, 50.05888021, 1],
[1.684574272, 56.54508738, 1],
[1.733258930, 37.51218759, 0],
[1.757899659, 57.36242239, 0],
[1.913337705, 69.30724639, 1],
[1.456048343, 69.34233711, 0]]

matriz_imc = np.array(lista_artificial)
matriz_imc

array([[ 1.78881069, 65.64810194,  0.        ],
       [ 1.56678443, 76.64276798,  0.        ],
       [ 2.09219306, 55.46818533,  1.        ],
       [ 1.78247092, 67.28199736,  1.        ],
       [ 1.73576698, 69.28900763,  0.        ],
       [ 1.68697465, 56.84005114,  0.        ],
       [ 1.79710463, 65.20897328,  1.        ],
       [ 1.18734906, 48.16476395,  0.        ],
       [ 1.59589144, 45.41064814,  1.        ],
       [ 1.39628178, 67.93011334,  0.        ],
       [ 1.60614817, 67.7196041 ,  0.        ],
       [ 1.70758997, 45.60933262,  0.        ],
       [ 1.73551312, 64.84545151,  0.        ],
       [ 1.67205518, 39.7059515 ,  1.        ],
       [ 1.72337707, 50.05888021,  1.        ],
       [ 1.68457427, 56.54508738,  1.        ],
       [ 1.73325893, 37.51218759,  0.        ],
       [ 1.75789966, 57.36242239,  0.        ],
       [ 1.9133377 , 69.30724639,  1.        ],
       [ 1.45604834, 69.34233711,  0.        ]])

Agora utilize esta matriz para calcular o IMC, utilizando a equação

```
IMC = peso / altura**2
```
e insira na nova tabela

In [86]:
altura = matriz_imc[:,0].astype(float)
peso = matriz_imc[:,1].astype(float)
sexo = matriz_imc[:,2].astype(float)

IMC = peso/np.power(altura, 2)
# IMC = np.insert(IMC.astype(str), 0, 'IMC')

new_table = np.column_stack([matriz_imc, IMC])

print(new_table)

[[ 1.78881069 65.64810194  0.         20.51603397]
 [ 1.56678443 76.64276798  0.         31.22142238]
 [ 2.09219306 55.46818533  1.         12.67186232]
 [ 1.78247092 67.28199736  1.         21.17648966]
 [ 1.73576698 69.28900763  0.         22.9975461 ]
 [ 1.68697465 56.84005114  0.         19.97272618]
 [ 1.79710463 65.20897328  1.         20.19113045]
 [ 1.18734906 48.16476395  0.         34.16430689]
 [ 1.59589144 45.41064814  1.         17.82998641]
 [ 1.39628178 67.93011334  0.         34.84305286]
 [ 1.60614817 67.7196041   0.         26.25083963]
 [ 1.70758997 45.60933262  0.         15.6417928 ]
 [ 1.73551312 64.84545151  0.         21.52899308]
 [ 1.67205518 39.7059515   1.         14.20215982]
 [ 1.72337707 50.05888021  1.         16.85467996]
 [ 1.68457427 56.54508738  1.         19.92574428]
 [ 1.73325893 37.51218759  0.         12.48663735]
 [ 1.75789966 57.36242239  0.         18.56262193]
 [ 1.9133377  69.30724639  1.         18.93195156]
 [ 1.45604834 69.34233711  0.  

In [87]:
nova_tabela = matriz_imc[:, 1]/(matriz_imc[:, 0]**2)
nova_tabela

array([20.51603397, 31.22142238, 12.67186232, 21.17648966, 22.9975461 ,
       19.97272618, 20.19113045, 34.16430689, 17.82998641, 34.84305286,
       26.25083963, 15.6417928 , 21.52899308, 14.20215982, 16.85467996,
       19.92574428, 12.48663735, 18.56262193, 18.93195156, 32.70746506])

In [88]:
imc = matriz_imc[:,1]/(matriz_imc[:,0]**2)
imc = np.concatenate((matriz_imc, imc.reshape(-1,1)), axis=1)
print(imc)

[[ 1.78881069 65.64810194  0.         20.51603397]
 [ 1.56678443 76.64276798  0.         31.22142238]
 [ 2.09219306 55.46818533  1.         12.67186232]
 [ 1.78247092 67.28199736  1.         21.17648966]
 [ 1.73576698 69.28900763  0.         22.9975461 ]
 [ 1.68697465 56.84005114  0.         19.97272618]
 [ 1.79710463 65.20897328  1.         20.19113045]
 [ 1.18734906 48.16476395  0.         34.16430689]
 [ 1.59589144 45.41064814  1.         17.82998641]
 [ 1.39628178 67.93011334  0.         34.84305286]
 [ 1.60614817 67.7196041   0.         26.25083963]
 [ 1.70758997 45.60933262  0.         15.6417928 ]
 [ 1.73551312 64.84545151  0.         21.52899308]
 [ 1.67205518 39.7059515   1.         14.20215982]
 [ 1.72337707 50.05888021  1.         16.85467996]
 [ 1.68457427 56.54508738  1.         19.92574428]
 [ 1.73325893 37.51218759  0.         12.48663735]
 [ 1.75789966 57.36242239  0.         18.56262193]
 [ 1.9133377  69.30724639  1.         18.93195156]
 [ 1.45604834 69.34233711  0.  

In [90]:
imc = len(matriz_imc)*[0]
for i in range(len(matriz_imc)):
    imc[i] = matriz_imc[i,1]/(matriz_imc[i,0]**2)

imc_dados = np.array(imc)
np.column_stack((matriz_imc,imc_dados))

array([[ 1.78881069, 65.64810194,  0.        , 20.51603397],
       [ 1.56678443, 76.64276798,  0.        , 31.22142238],
       [ 2.09219306, 55.46818533,  1.        , 12.67186232],
       [ 1.78247092, 67.28199736,  1.        , 21.17648966],
       [ 1.73576698, 69.28900763,  0.        , 22.9975461 ],
       [ 1.68697465, 56.84005114,  0.        , 19.97272618],
       [ 1.79710463, 65.20897328,  1.        , 20.19113045],
       [ 1.18734906, 48.16476395,  0.        , 34.16430689],
       [ 1.59589144, 45.41064814,  1.        , 17.82998641],
       [ 1.39628178, 67.93011334,  0.        , 34.84305286],
       [ 1.60614817, 67.7196041 ,  0.        , 26.25083963],
       [ 1.70758997, 45.60933262,  0.        , 15.6417928 ],
       [ 1.73551312, 64.84545151,  0.        , 21.52899308],
       [ 1.67205518, 39.7059515 ,  1.        , 14.20215982],
       [ 1.72337707, 50.05888021,  1.        , 16.85467996],
       [ 1.68457427, 56.54508738,  1.        , 19.92574428],
       [ 1.73325893, 37.

In [94]:
# np_array = np.array(array)
# print(type(np_array))
imc = matriz_imc[:,1:3:20] / (matriz_imc[:,0:1:20] **2)
imc.reshape(-1,1)
np_array = np.concatenate((matriz_imc , imc.reshape(-1,1)), axis= 1)
np_array

array([[ 1.78881069, 65.64810194,  0.        , 20.51603397],
       [ 1.56678443, 76.64276798,  0.        , 31.22142238],
       [ 2.09219306, 55.46818533,  1.        , 12.67186232],
       [ 1.78247092, 67.28199736,  1.        , 21.17648966],
       [ 1.73576698, 69.28900763,  0.        , 22.9975461 ],
       [ 1.68697465, 56.84005114,  0.        , 19.97272618],
       [ 1.79710463, 65.20897328,  1.        , 20.19113045],
       [ 1.18734906, 48.16476395,  0.        , 34.16430689],
       [ 1.59589144, 45.41064814,  1.        , 17.82998641],
       [ 1.39628178, 67.93011334,  0.        , 34.84305286],
       [ 1.60614817, 67.7196041 ,  0.        , 26.25083963],
       [ 1.70758997, 45.60933262,  0.        , 15.6417928 ],
       [ 1.73551312, 64.84545151,  0.        , 21.52899308],
       [ 1.67205518, 39.7059515 ,  1.        , 14.20215982],
       [ 1.72337707, 50.05888021,  1.        , 16.85467996],
       [ 1.68457427, 56.54508738,  1.        , 19.92574428],
       [ 1.73325893, 37.

| IMC             | Categoria           |   |
|-----------------|---------------------|---|
| abaixo de 16,00 | Baixo peso Grau III |   |
| 16,00 a 16,99   | Baixo peso Grau II  |   |
| 17,00 a 18.49   | Baixo peso Grau I   |   |
| 18,50 a 24,99   | Peso ideal          |   |
| 25,00 a 29,99   | Sobrepeso           |   |
| 30,00 a 34,99   | Obesidade Grau I    |   |
| 35,00 a 39,99   | Obesidade Grau II   |   |
| 40,0 e acima    | Obesidade Grau III  |   |

Agora utilize a tabela acima para indicar a qual categoria cada valor de IMC se enquadra. Insira novamente na tabela.

In [96]:
cat = []
for i in np_array:
    if i[3] <16:
        cat.append('Baixo peso Grau III')
    elif i[3] <17:
        cat.append('Baixo peso Grau II')
    elif i[3] <18.5:
        cat.append('Baixo peso Grau I')
    elif i[3] <25:
        cat.append('Peso Ideal')
    elif i[3] <30:
        cat.append('Sobrepeso')
    elif i[3] <35:
        cat.append('Obesidade Grau I')
    elif i[3] <40:
        cat.append('Obesidade Grau II')
    else :
        cat.append('Obesidade Grau III')
cat = np.array(cat)

tab = np.append(np_array, cat.reshape(-1, 1), axis=1)
print(tab)

[['1.788810693' '65.64810194' '0.0' '20.51603396583262' 'Peso Ideal']
 ['1.566784434' '76.64276798' '0.0' '31.221422379708287'
  'Obesidade Grau I']
 ['2.092193055' '55.46818533' '1.0' '12.671862320992751'
  'Baixo peso Grau III']
 ['1.782470917' '67.28199736' '1.0' '21.176489656761625' 'Peso Ideal']
 ['1.735766977' '69.28900763' '0.0' '22.997546096415384' 'Peso Ideal']
 ['1.686974648' '56.84005114' '0.0' '19.972726177686557' 'Peso Ideal']
 ['1.797104633' '65.20897328' '1.0' '20.191130448388307' 'Peso Ideal']
 ['1.187349055' '48.16476395' '0.0' '34.1643068868657' 'Obesidade Grau I']
 ['1.595891436' '45.41064814' '1.0' '17.82998641150157'
  'Baixo peso Grau I']
 ['1.396281776' '67.93011334' '0.0' '34.843052856738055'
  'Obesidade Grau I']
 ['1.606148165' '67.7196041' '0.0' '26.250839625439873' 'Sobrepeso']
 ['1.707589967' '45.60933262' '0.0' '15.64179279721665'
  'Baixo peso Grau III']
 ['1.735513116' '64.84545151' '0.0' '21.528993081895386' 'Peso Ideal']
 ['1.672055182' '39.7059515' '1

In [97]:
def imc_calculate(imc: int) -> np.array:
    if imc < 16:
        return np.array("Baixo peso Grau III", dtype='<U32')
    elif 16 <= imc < 17:
        return np.array("Baixo peso Grau II", dtype='<U32')
    elif 17 <= imc < 18.5:
        return np.array("Baixo peso Grau I", dtype='<U32')
    elif 18.5 <= imc < 24.5:
        return np.array("Peso ideal", dtype='<U32')
    elif 24.5 <= imc < 30:
        return np.array("Sobrepeso", dtype='<U32')
    elif 30 <= imc < 35:
        return np.array("Obesidade Grau I", dtype='<U32')
    elif 35 <= imc < 40:
        return np.array("Obesidade Grau II", dtype='<U32')
    elif imc >= 40:
        return np.array("Obesidade Grau III", dtype='<U32')

nova_tabela = matriz_imc[:, 1]/np.power(matriz_imc[:, 0], 2)
nova_tabela = np.column_stack([matriz_imc, nova_tabela])

categorias = np.apply_along_axis(imc_calculate, 1, nova_tabela[:, -1].reshape(-1, 1))
nova_tabela = np.column_stack([nova_tabela, categorias])
del categorias
nova_tabela

array([['1.788810693', '65.64810194', '0.0', '20.51603396583262',
        'Peso ideal'],
       ['1.566784434', '76.64276798', '0.0', '31.221422379708287',
        'Obesidade Grau I'],
       ['2.092193055', '55.46818533', '1.0', '12.671862320992751',
        'Baixo peso Grau III'],
       ['1.782470917', '67.28199736', '1.0', '21.176489656761625',
        'Peso ideal'],
       ['1.735766977', '69.28900763', '0.0', '22.997546096415384',
        'Peso ideal'],
       ['1.686974648', '56.84005114', '0.0', '19.972726177686557',
        'Peso ideal'],
       ['1.797104633', '65.20897328', '1.0', '20.191130448388307',
        'Peso ideal'],
       ['1.187349055', '48.16476395', '0.0', '34.1643068868657',
        'Obesidade Grau I'],
       ['1.595891436', '45.41064814', '1.0', '17.82998641150157',
        'Baixo peso Grau I'],
       ['1.396281776', '67.93011334', '0.0', '34.843052856738055',
        'Obesidade Grau I'],
       ['1.606148165', '67.7196041', '0.0', '26.250839625439873',
    

### Tipos de dados

Primeiro vamos falar do infinito (e além).

Quando fazemos operações de ponto flutuante no computador, existe um padrão técnico (definido pela IEEE, o Instituto de Engenheiros Eletro-eletrônicos) que define algumas coisas que uma biblioteca tem que ter.

Especificamente, aqui vamos falar de duas coisas:
- Not a Number (NAN)
- Infinito

In [98]:
# Not a Number é o resultado de operações inválidas.
# Embora ele exista no Python, operações inválidas tendem a levantar um erro.
0/0

ZeroDivisionError: division by zero

In [99]:
# Para usá-lo no python, temos que converter string para float.
float('NaN')

nan

In [100]:
# No numpy, temos o objeto nan.
print(np.nan)
print(type(np.nan))

nan
<class 'float'>


In [101]:
# Já no numpy, operações inválidas retornam NaN mesmo.
x1 = np.array([1, 0, 1, 0])
x2 = np.array([2, 1, 2, 0])

print(x1 / x2)

[0.5 0.  0.5 nan]


C:\Users\nagamatu\AppData\Local\Temp\ipykernel_8332\1780719695.py:5: RuntimeWarning: invalid value encountered in true_divide
  print(x1 / x2)


In [102]:
# "Infinito", no padrão, pode ser pensado como um número que é maior que qualquer outro número.
# No caso de "-infinito", temos um número que é menor que qualquer outro número.
1/0

ZeroDivisionError: division by zero

In [103]:
print(float('inf'))
print(float('inf') > 293818943824723984.928)
print(-float('inf') < -293818943824723984.928)

inf
True
True


In [104]:
# No Numpy, não seria diferente.
print(np.inf)
print(np.inf > 293818943824723984.928)
print(-np.inf < -293818943824723984.928)
print(type(np.inf))

inf
True
True
<class 'float'>


In [105]:
# No numpy, algumas operações podem gerar infinitos.
x1 = np.array([1, 0, 1, 0])
x2 = np.array([2, 1, 2, 0])

print(x2 / x1)

[ 2. inf  2. nan]


C:\Users\nagamatu\AppData\Local\Temp\ipykernel_8332\1085014809.py:5: RuntimeWarning: divide by zero encountered in true_divide
  print(x2 / x1)
C:\Users\nagamatu\AppData\Local\Temp\ipykernel_8332\1085014809.py:5: RuntimeWarning: invalid value encountered in true_divide
  print(x2 / x1)


Notou que tanto infinito quanto NaN são do tipo "float"? Não são float64, nem float32, nem anda assim.

Isso é devido à hierarquia de dtypes do numpy.

![hierarchy](https://numpy.org/doc/stable/_images/dtype-hierarchy.png)